// js/data.js
export const supervisors = [
  {
    id: 1,
    name: "Dr. Ali Khan",
    researchDomain: "Artificial Intelligence",
    availableSlots: 3,
    contactInfo: "ali.khan@university.edu",
  },
  {
    id: 2,
    name: "Dr. Sara Ahmed",
    researchDomain: "Data Science",
    availableSlots: 0,
    contactInfo: "sara.ahmed@university.edu",
  },
  {
    id: 3,
    name: "Dr. John Smith",
    researchDomain: "Machine Learning",
    availableSlots: 2,
    contactInfo: "john.smith@university.edu",
  },
  {
    id: 4,
    name: "Dr. Emily Brown",
    researchDomain: "Cybersecurity",
    availableSlots: 1,
    contactInfo: "emily.brown@university.edu",
  },
  {
    id: 5,
    name: "Dr. Michael Johnson",
    researchDomain: "Software Engineering",
    availableSlots: 4,
    contactInfo: "michael.johnson@university.edu",
  },
  {
    id: 6,
    name: "Dr. Sarah Lee",
    researchDomain: "Human-Computer Interaction",
    availableSlots: 2,
    contactInfo: "sarah.lee@university.edu",
  },
  {
    id: 7,
    name: "Dr. David Wilson",
    researchDomain: "Cloud Computing",
    availableSlots: 3,
    contactInfo: "david.wilson@university.edu",
  },
  {
    id: 8,
    name: "Dr. Laura Martinez",
    researchDomain: "Natural Language Processing",
    availableSlots: 1,
    contactInfo: "laura.martinez@university.edu",
  },
  {
    id: 9,
    name: "Dr. James Anderson",
    researchDomain: "Computer Vision",
    availableSlots: 0,
    contactInfo: "james.anderson@university.edu",
  },
  {
    id: 10,
    name: "Dr. Olivia Taylor",
    researchDomain: "Blockchain Technology",
    availableSlots: 2,
    contactInfo: "olivia.taylor@university.edu",
  },
];